apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: web-j4
  name: web-j4
  namespace: www
spec:
  replicas: 2
  selector:
    matchLabels:
      run: web-j4
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: web-j4
    spec:
      containers:
      - image: 458891109543.dkr.ecr.us-east-1.amazonaws.com/web-j4:0.1.0
        name: web-j4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
