apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: www
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: 458891109543.dkr.ecr.us-east-1.amazonaws.com/dnlloyd:web_nginx
        name: www
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
          - name: regcred
