---
# Source: web-kz/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-kz
  labels:
    helm.sh/chart: web-kz-0.3.0
    app.kubernetes.io/name: web-kz
    app.kubernetes.io/instance: web-kz
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web-kz
      app.kubernetes.io/instance: web-kz
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-kz
        app.kubernetes.io/instance: web-kz
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: default
      securityContext:
        null
      containers:
        - name: web-kz
          securityContext:
            null
          image: "458891109543.dkr.ecr.us-east-1.amazonaws.com/web-j4:0.1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            null
