apiVersion: v1
kind: Service
metadata:
  name: web-kz
  labels:
    app: web-kz
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-kz
